version: '3.8'

services:
  api:
    image: vvsaltykov/ratspapi:latest
    ports:
      - "32770:8080"
    depends_on:
      - gross-service
      - kafka
    networks:
      - ratsp-network
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ratspdb;Username=postgres;Password=MyPassword123!
      - Kafka__BootstrapServers=kafka:9092
      - Redis__Connection=redis:6379


  gross-service:
    image: vvsaltykov/ratspgrossservice:latest
    depends_on:
      - kafka
    networks:
      - ratsp-network
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - Redis__Connection=redis:6379
  
  
  webclient:
    image: vvsaltykov/ratspwebclient:latest
    ports:
      - "32771:8080"
    depends_on:
      - kafka
    networks:
      - ratsp-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ratspdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyPassword123!
    ports:
      - "5432:5432"
    networks:
      - ratsp-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    networks:
      - ratsp-network

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - ratsp-network
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ratsp-network

networks:
  ratsp-network:
    driver: bridge